package export_server

import (
	"time"
)

// ExportParams represents all the parameters for a Terraform export job
type ExportParams struct {
	Directory                      string   `json:"directory"`
	IncludeFilterResources         []string `json:"include_filter_resources,omitempty"`
	ExcludeFilterResources         []string `json:"exclude_filter_resources,omitempty"`
	ReplaceWithDatasource          []string `json:"replace_with_datasource,omitempty"`
	IncludeStateFile               bool     `json:"include_state_file"`
	ExportAsHCL                    bool     `json:"export_as_hcl,omitempty"`
	ExportFormat                   string   `json:"export_format"`
	SplitFilesByResource           bool     `json:"split_files_by_resource"`
	LogPermissionErrors            bool     `json:"log_permission_errors"`
	ExcludeAttributes              []string `json:"exclude_attributes,omitempty"`
	EnableDependencyResolution     bool     `json:"enable_dependency_resolution"`
	IgnoreCyclicDeps               bool     `json:"ignore_cyclic_deps"`
	Compress                       bool     `json:"compress"`
	ExportComputed                 bool     `json:"export_computed"`
	UseLegacyArchitectFlowExporter bool     `json:"use_legacy_architect_flow_exporter"`
}

// JobStatus represents the current status of an export job
type JobStatus struct {
	JobID        string     `json:"job_id"`
	Status       string     `json:"status"`
	Progress     int        `json:"progress,omitempty"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
	CompletedAt  *time.Time `json:"completed_at,omitempty"`
	CancelledAt  *time.Time `json:"cancelled_at,omitempty"`
	ErrorMessage string     `json:"error_message,omitempty"`
}

// JobResults represents the results of a completed export job
type JobResults struct {
	JobID           string       `json:"job_id"`
	Status          string       `json:"status"`
	Files           []ExportFile `json:"files"`
	ExportDirectory string       `json:"export_directory"`
}

// ExportFile represents a file generated by the export process
type ExportFile struct {
	Name string `json:"name"`
	Size int64  `json:"size"`
	Type string `json:"type"`
}

// CreateJobRequest represents the request to create a new export job
type CreateJobRequest struct {
	ExportParams
}

// CreateJobResponse represents the response when creating a new export job
type CreateJobResponse struct {
	JobID     string    `json:"job_id"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

// ErrorResponse represents an error response from the API
type ErrorResponse struct {
	Error   string `json:"error"`
	Message string `json:"message,omitempty"`
}

// Job states
const (
	JobStatusPending   = "pending"
	JobStatusRunning   = "running"
	JobStatusCompleted = "completed"
	JobStatusFailed    = "failed"
	JobStatusCancelled = "cancelled"
)

// Export formats
const (
	ExportFormatHCL     = "hcl"
	ExportFormatJSON    = "json"
	ExportFormatJSONHCL = "json_hcl"
	ExportFormatHCLJSON = "hcl_json"
)
