// This file has been autogenerated. The following properties could not be retrieved from the API or would not make sense in a different org e.g. Edge IDs
// The variables contained in this file have been given default values and should be edited as necessary

genesyscloud_flow_Dave_-_SFDC_Service_-_v2_Basic_filepath = ""