@Library('pipeline-library') _
pipeline {
    agent {
        node{
            label "dev_mesos_large_v2"
        }
    }

    environment {
        CREDENTIALS_ID  = "GENESYSCLOUD_OAUTHCLIENT_ID_AND_SECRET"
        GOPATH = "$HOME/go"
		TF_ACC = "1"
        TF_LOG = "DEBUG"
        TF_LOG_PATH = "../test.log"
		GENESYSCLOUD_REGION = "us-east-1"
        GENESYSCLOUD_SDK_DEBUG =  "true"
        GENESYSCLOUD_TOKEN_POOL_SIZE =  20
    }
    tools {
        go 'Go 1.20'
        terraform 'Terraform 1.0.10'
    }

    stages {
      
        
        stage('Install Dependencies & Build') {
            steps {
                echo 'Installing dependencies'
                sh 'go version'
                sh 'go mod download'
                sh 'go build -v .'
            }
	    }

        stage('Terraform Check') {
            steps {
                echo 'Check Terraform Installation'
                sh 'terraform -version'

            }
        }

        stage('Change Directory to Root') {
            steps {
                sh 'cd ../../'

            }
        } 

        stage('Unit Tests') {
            steps {
            
                catchError(buildResult: 'FAILURE', stageResult:'FAILURE'){
                    echo 'Attempting to Run Unit Tests'
                    withCredentials([usernamePassword(credentialsId: CREDENTIALS_ID, usernameVariable: 'GENESYSCLOUD_OAUTHCLIENT_ID',passwordVariable:'GENESYSCLOUD_OAUTHCLIENT_SECRET')])
                        {

                            env.TF_UNIT=1
                            echo 'Loading Genesys OAuth Credentials'
                            sh 'go test ./genesyscloud/team -run TestUnit -v -timeout 15m -count=1 -cover -coverprofile=coverageUnit.out'                            

 
                        }

                }

            }
        }


        stage('Acceptance Tests') {
            steps {
            
                catchError(buildResult: 'SUCCESS', stageResult:'FAILURE'){
                    echo 'Attempting to Run Tests'
                    withCredentials([usernamePassword(credentialsId: CREDENTIALS_ID, usernameVariable: 'GENESYSCLOUD_OAUTHCLIENT_ID',passwordVariable:'GENESYSCLOUD_OAUTHCLIENT_SECRET')])
                        {
                            env.TF_ACC=1
                            echo 'Loading Genesys OAuth Credentials'
                            sh 'go test ./genesyscloud/team -run TestAcc -v -timeout 80m -cover -coverprofile=coverageAcceptance.out'                            
                        }

                }

            }
        }

        stage('Generate Readable Coverage Report') {
            steps {
                sh 'go tool cover -html coverageAcceptance.out -o coverageAcceptance.html'

            }
        }


        stage('Upload Coverage Report') {
            steps {
                archiveArtifacts artifacts: 'coverageAcceptance.html', allowEmptyArchive: true

            }
        }


    } 
}
