name: Ensure Documentation in Sync
on:
  push:
    paths-ignore:
      - 'README.md'
jobs:
  # ensure the documentation is up to date
  generate:
    name: Generate
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'
        id: go

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3.0.0
        with:
          terraform_wrapper: false
          terraform_version: ${{ matrix.terraform }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: |
          go mod download

      - name: Generate
        run: |
          go generate
          if [[ -n $(git status -s) ]]; then
              echo "There are untracked documentation changes:\n"
              git status
              exit 1
          fi