#!/bin/sh

STAGED_GO_FILES=$(git diff --cached --name-only -- '*.go')
if [[ $STAGED_GO_FILES == "" ]]; then
    echo "no go files updated"
else
    echo "Formatting and vetting code go files"
    for file in $STAGED_GO_FILES; do
        go fmt $file
        go vet ./...
        git add $file
    done
fi